### ISSUE TITLE
Add a method to get the name of the animation/clip/marker

### ISSUE THREAD

**Issue by mirsella** [merwaaan/bevy_spritesheet_animation#18]
Hello !

Something like `get_name_from_animation(&self, animation_id: &AnimationId) -> Option<String>` ?

I can do a pr with these changes if you find this to be useful

the code would just be
```rs
self
.animation_name_lookup
.iter()
.find_map(|(k, v)| if v == animation_id { Some(k) } else { None })
```
(find_map return an `Option<String> `)

**Comment by merwaaan** [comment]
I think that we laready have that :)

https://github.com/merwaaan/bevy_spritesheet_animation/blob/32b23fb8f9f9496de03d9d01c1bc1e7d23e3d6d9/src/library.rs#L302

(same for clips and markers)

**Comment by mirsella** [comment]
yeah my bad i confused my self lmao, i edited the title and message...

**Comment by merwaaan** [comment]
Sure, I'd gladly accept a PR!

Now that I'm thinking about it, an animation/clip/marker can currently have multiple names. You can call `name_XXX()` multiple times with different names, and each name will reference the same item.

This means that with the current state of things, a `get_animation/clip/marker_name()` API should return a list of names.

**BUT** in practice I don't see any real use-case for having multiple names so this PR might be a good time to simplify everything, replace the current name instead of adding a new one when calling `name_XXX()`, and having `get_XXX_name()` return just an Option<String>, as you suggested.

**Comment by mirsella** [comment]
so:
- create the get_XXX_name() method
- name_XXX() method replace the name or insert the name. we can swap the hashmap to be a hashmap<AnimationId, String> since there can be only one AnimationId now ?

**Comment by merwaaan** [comment]
> - create the get_XXX_name() method
> - name_XXX() method replace the name or insert the name. we can swap the hashmap to be a hashmap<AnimationId, String> since there can be only one AnimationId now ?

Sounds good!
