### ISSUE TITLE
SpritesheetLibrary::new_clip

### ISSUE THREAD

**Issue by UkoeHB** [merwaaan/bevy_spritesheet_animation#4]
Had some issues with this method.
- You cannot make marker IDs in the method because the library is borrowed as mutable to call `new_clip`. A reference to the library from within the closure would solve that.
- You cannot access anything mutably in the closure since it's a `Fn` method. It should only need to be a `FnOnce`.

**Comment by merwaaan** [comment]
@UkoeHB Thanks for the feedback!

- I'm afraid that adding the library as a parameter would make things more verbose and would not add much in terms of ergonomics. What's your use-case for creating markers inside of `new_clip` instead of before the call?

- I'm not too familiar with the subtleties of closures. Does using `FnMut` instead of `Fn`/`FnOnce` seem reasonnable? I have this working in a branch, but I just want some input since you seem more confortable with the topic.

**Comment by merwaaan** [comment]
@UkoeHB Creating animations has been made way more straightforward with the latest commits so things should be easier for you now.
